source "http://rubygems.org"

gem "json"
gem "thin"
gem "sinatra"
gem "extlib"
gem "sinatra-reloader"
gem "sinatra-content-for"
gem "sinatra-static-assets" , "0.5.0"
gem "tokyocabinet"
gem "sinatra-auto-reload"
